apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwcopeland-web
  namespace: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hwcopeland-web
  template:
    metadata:
      labels:
        app: hwcopeland-web
    spec:
      containers:
        - name: hwcopeland-web
          image: hwcopeland/hwcopeland-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hwcopeland-web
  namespace: web-server
spec:
  selector:
    app: hwcopeland-web
  type: ClusterIP
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hwcopeland-web
  namespace: web-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "cf-issuer"
spec:
  ingressClassName: nginx
  rules:
    - host: info.hwcopeland.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hwcopeland-web
                port:
                  number: 3000
  tls:
    - hosts:
        - "info.hwcopeland.net"
      secretName: cf-wildcard-cert-secret
